eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
    registry-fetch-interval-seconds: 3
spring:
      datasoource:
        url: jdbc:mysql://127.0.0.1:3306/sms-gatway
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            format_sql: true
        
