eureka:
  client:
    service-url:
      defaultZone: http://discovery:8888/eureka/
    registry-fetch-interval-seconds: 3
spring:

  cloud: 
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:  "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
            allowedHeaders:  "*"
            
            
           
            
  
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://mysql_container:3306/smsGateway
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
