server:
  port: 7001
  compression:
    enabled: false
eureka:
  client:
    register-with-eureka: true

spring:
  cloud:
    gateway:
      globalCors:
        corsConfigurations:
          ["/**"]:
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            
      mvc:
        routes:
          - id: group
            uri: lb://GROUP
            predicates:
              - Path=/groups/**
            filters:
              - StripPrefix=1
              - AddRequestHeader=Authorization, Bearer ${token}

          - id: history
            uri: lb://HISTORY
            predicates:
              - Path=/histories/**
            filters:
              - StripPrefix=1
              - AddRequestHeader=Authorization, Bearer ${token}
          - id: receiver
            uri: lb://receiver
            predicates:
              - Path=/receivers/**
            filters:
              - StripPrefix=1
              - AddRequestHeader=Authorization, Bearer ${token}
          - id: schedule
            uri: lb://SCHEDULE
            predicates:
              - Path=/schedule/**
            filters:
              - StripPrefix=1
              - AddRequestHeader=Authorization, Bearer ${token}
          - id: sendmsg
            uri: lb://SendMsg
            predicates:
              - Path=/sendmsg/**
            filters:
              - StripPrefix=1
              - AddRequestHeader=Authorization, Bearer ${token}
