server:
  port: 7001
  compression:
    enabled: false 
eureka:
  client:
    register-with-eureka: true

logging:
  level:
    org.apache.hc.client5: DEBUG
    org.apache.hc.core5: DEBUG
spring:
  cloud:
    gateway:
      httpclient:
        response-timeout: 30s  # Default is 5s
        connect-timeout: 5s
        pool:
          max-idle-time: 60s
      mvc:
        routes:
        - id: auth
          uri: lb://AUTH
          predicates:
              - Path=/AUTH/**
          filters:
              - StripPrefix=1
        - id: group
          uri: lb://GROUP
          predicates:
              - Path=/GROUP/**
          filters:
              - StripPrefix=1
          
        - id: history
          uri: lb://HISTORY
          predicates:
            - Path=/history/**
          filters:
              - StripPrefix=1
        - id: receiver
          uri: lb://RECIVER
          predicates:
              - Path=/receiver/**
          filters:
              - StripPrefix=1
        - id: schedule
          uri: lb://SCHEDULE
          predicates:
              - Path=/SCHEDULE/**
          filters:
              - StripPrefix=1
        - id: sendmsg
          uri: lb://SENDMSG
          predicates:
              - Path=/SENDMSG/**
          filters:
              - StripPrefix=1

