server:
  port: 7001
eureka:
  client:
    register-with-eureka: true
spring:
  cloud:
    gateway:
      httpclient:
        max-in-memory-buffer-size: 10MB  # For larger payloads
      routes:
        - id: auth
          uri: lb://AUTH  # Ensure Eureka registration matches
          predicates:
            - Path=/AUTH/**
          filters:
            - StripPrefix=1
        - id: group
          uri: lb://group  # Lowercase if service is registered as 'group'
          predicates:
            - Path=/group/**
          filters:
            - StripPrefix=1
        - id: history
          uri: lb://history
          predicates:
            - Path=/history/**
          filters:
            - StripPrefix=1