server:
  port: 7001
eureka:
  client:
    register-with-eureka: false
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: history
            uri: lb://HISTORY
            predicates:
              - Path=/history/**
            filters:
              - StripPrefix=1
